name: Snapshots

on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

jobs:
  generate-snapshots:
    name: Generate snapshot
    runs-on: ubuntu-latest
    strategy:
      matrix:
        playbook:
          - snapshots_crab
          - snapshots_darwinia
    steps:
      - uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ansible
          playbook: playbooks/${{ matrix.playbook }}/playbook.yml
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          options: --user ansible --verbose --diff
